Update deploy_pipeline.yml

diff --git a/.github/workflows/deploy_pipeline.yml b/.github/workflows/deploy_pipeline.yml
--- a/.github/workflows/deploy_pipeline.yml
+++ b/.github/workflows/deploy_pipeline.yml
@@ -11,6 +11,12 @@ jobs:
     name: Deploy
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     runs-on: ubuntu-latest
+    env:
+      OCI_CLI_USER: ${{secrets.OCI_USER_OCID}}
+      OCI_CLI_TENANCY: ${{secrets.OCI_TENANCY_OCID}}
+      OCI_CLI_FINGERPRINT: ${{secrets.OCI_FINGERPRINT}}
+      OCI_CLI_KEY_CONTENT: ${{secrets.OCI_CLI_KEY_CONTENT}}
+      OCI_CLI_REGION: ${{secrets.OCI_REGION}}
     strategy:
       matrix:
         Deploy: [true]
@@ -32,90 +38,102 @@ jobs:
         echo "key_file=~/.oci/gallant.thomas@outlook.com_2022-10-25T03_23_41.205Z.pem" >> ~/.oci/config
         echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/gallant.thomas@outlook.com_2022-10-25T03_23_41.205Z.pem
         echo "${{secrets.VM_SSH_PUB_KEY}}" >> /home/runner/.oci/Springboot.pub
-    
-    - name: 'Install OCI CLI'
-      run: |
-        curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
-        chmod +x install.sh
-        ./install.sh --accept-all-defaults
-        echo "/home/runner/bin" >> $GITHUB_PATH
-        exec -l $SHELL
-      
-    - name: 'Fix Config File Permissions'
-      run: |
-       oci setup repair-file-permissions --file /home/runner/.oci/config
-       oci setup repair-file-permissions --file /home/runner/.oci/gallant.thomas@outlook.com_2022-10-25T03_23_41.205Z.pem
-      
-    - name: 'Check Existing Instance'
-      run: |
-        echo "INSTANCE_OCID=$( \
-          oci compute instance list \
-          --lifecycle-state RUNNING \
-          --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
-          --display-name cicd-demo \
-          --query "data [0].id" \
-          --raw-output \
-        )" >> $GITHUB_ENV
-      
-    - name: 'Create Instance'
+        
+    - name: Create Instance
       if: ${{!env.INSTANCE_OCID}}
-      run: |
-        echo "INSTANCE_OCID=$( \
-          oci compute instance launch \
-            --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
-            --availability-domain ${{secrets.VM_AVAILABILITY_DOMAIN}} \
-            --shape ${{secrets.VM_SHAPE}} \
-            --assign-public-ip true \
-            --display-name springboot \
-            --ssh-authorized-keys-file /home/runner/.oci/Springboot.pub \
-            --subnet-id ${{secrets.VM_SUBNET_OCID}} \
-            --wait-for-state RUNNING \
-            --query "data.id" \
-            --raw-output \
-        )" >> GITHUB_ENV
-        
-    - name: 'Get Instance IP'
-      run: |
-        echo "INSTANCE_IP=$( \
-          oci compute instance list-vnics \
-          --instance-id ${{env.INSTANCE_OCID}} \
-          --query 'data [0]."public-ip"' \
-          --raw-output \
-        )" >> $GITHUB_ENV
-        echo Instance IP: ${{ env.INSTANCE_IP }}
-        
-    - name: 'Wait for SSH'
-      run: |
-        while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
-                sleep 5
-                echo "SSH not available..."
-        done; echo "SSH ready!"
-        
-    - name: 'Stop App'
-      uses: appleboy/ssh-action@master
+      uses: oracle-actions/run-oci-cli-command@v1.1
+      id: Create Instance
       with:
-        host: ${{ env.INSTANCE_IP }}
-        username: opc
-        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
-        script: |
-          pid=`ps aux | grep "[c]Springboot.jar" | awk '{print $2}'`
-          if [ "$pid" == "" ]; then
-            echo "Process not found"
-          else
-            kill -9 $pid
-          fi
-          sudo mkdir -p /app
-          
-      # This probably won't work because it won't retrieve the jar file correctly
-#     - name: 'Push JAR'
-#       uses: appleboy/scp-action@master
+        command: 'oci compute instance launch --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} --availability-domain ${{secrets.VM_AVAILABILITY_DOMAIN}} --shape ${{secrets.VM_SHAPE}} --assign-public-ip true --display-name springboot --image-id ${{secrets.VM_CUSTOM_IMAGE_OCID}} --ssh-authorized-keys-file /home/runner/oci/Springboot.pub --subnet-id ${{secrets.VM_SUBNET_OCID}} --wait-for-state RUNNING --query "data.id" --raw-output'
+    
+        
+    
+    
+    
+    
+#     - name: 'Install OCI CLI'
+#       run: |
+#         curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
+#         chmod +x install.sh
+#         ./install.sh --accept-all-defaults
+#         echo "/home/runner/bin" >> $GITHUB_PATH
+#         exec -l $SHELL
+      
+#     - name: 'Fix Config File Permissions'
+#       run: |
+#        oci setup repair-file-permissions --file /home/runner/.oci/config
+#        oci setup repair-file-permissions --file /home/runner/.oci/gallant.thomas@outlook.com_2022-10-25T03_23_41.205Z.pem
+      
+#     - name: 'Check Existing Instance'
+#       run: |
+#         echo "INSTANCE_OCID=$( \
+#           oci compute instance list \
+#           --lifecycle-state RUNNING \
+#           --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
+#           --display-name cicd-demo \
+#           --query "data [0].id" \
+#           --raw-output \
+#         )" >> $GITHUB_ENV
+      
+#     - name: 'Create Instance'
+#       if: ${{!env.INSTANCE_OCID}}
+#       run: |
+#         echo "INSTANCE_OCID=$( \
+#           oci compute instance launch \
+#             --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
+#             --availability-domain ${{secrets.VM_AVAILABILITY_DOMAIN}} \
+#             --shape ${{secrets.VM_SHAPE}} \
+#             --assign-public-ip true \
+#             --display-name springboot \
+#             --ssh-authorized-keys-file /home/runner/.oci/Springboot.pub \
+#             --subnet-id ${{secrets.VM_SUBNET_OCID}} \
+#             --wait-for-state RUNNING \
+#             --query "data.id" \
+#             --raw-output \
+#         )" >> GITHUB_ENV
+        
+#     - name: 'Get Instance IP'
+#       run: |
+#         echo "INSTANCE_IP=$( \
+#           oci compute instance list-vnics \
+#           --instance-id ${{env.INSTANCE_OCID}} \
+#           --query 'data [0]."public-ip"' \
+#           --raw-output \
+#         )" >> $GITHUB_ENV
+#         echo Instance IP: ${{ env.INSTANCE_IP }}
+        
+#     - name: 'Wait for SSH'
+#       run: |
+#         while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
+#                 sleep 5
+#                 echo "SSH not available..."
+#         done; echo "SSH ready!"
+        
+#     - name: 'Stop App'
+#       uses: appleboy/ssh-action@master
 #       with:
 #         host: ${{ env.INSTANCE_IP }}
 #         username: opc
 #         key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
-#         source: "build/libs/cicd-demo-${{env.VERSION}}-all.jar"
-#         target: "app"
-#         strip_components: 2
+#         script: |
+#           pid=`ps aux | grep "[c]Springboot.jar" | awk '{print $2}'`
+#           if [ "$pid" == "" ]; then
+#             echo "Process not found"
+#           else
+#             kill -9 $pid
+#           fi
+#           sudo mkdir -p /app
+          
+#       # This probably won't work because it won't retrieve the jar file correctly
+# #     - name: 'Push JAR'
+# #       uses: appleboy/scp-action@master
+# #       with:
+# #         host: ${{ env.INSTANCE_IP }}
+# #         username: opc
+# #         key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+# #         source: "build/libs/cicd-demo-${{env.VERSION}}-all.jar"
+# #         target: "app"
+# #         strip_components: 2
         
 #     - name: 'Start App'
 #       uses: appleboy/ssh-action@master
